audio_hw_configurable: System include for host
BZ: 94617

Compilation error for host some system include are missing.

Add some system include in sources files needed for host compilation:
stdint.h, stdlib.h, errno.h, limits.h, algorithm

Change-Id: Ie7625cb55aeea3b27f4c0ad98dba473a96d33c2e
Signed-off-by: Jeremie Graulle <jeremiex.graulle@intel.com>
Reviewed-on: http://android.intel.com:8080/97600
Reviewed-by: Dixon, CharlesX <charlesx.dixon@intel.com>
Tested-by: Dixon, CharlesX <charlesx.dixon@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>